### ISSUE TITLE
Log Probability Negative Infinity

### ISSUE THREAD

**Issue by howardya** [kjartako/MS_VAR#3]
Hi,

I tried to run your examples. MS_VAR with USMacro example. I choose the LKJ prior.

However i have this problem,

Chain 1: Rejecting initial value:
Chain 1:   Log probability evaluates to log(0), i.e. negative infinity.
Chain 1:   Stan can't start sampling from this initial value.

Do you know what is the issue?

**Comment by howardya** [comment]
Hi @kjartako  I found out the issue.

In https://github.com/kjartako/MS_VAR/blob/77c3e9c57fcd5fcf6f8c51e334e1e2c612192e61/MS_VAR/Stan/MS_VAR_wishart.stan#L116

It should be the following instead
```
alphas[t-ARdim,i]=log_sum_exp(fwd[i,]); 
```

The second index has not been initialized yet, thus causing the error of negative infinity.

**Comment by kjartako** [comment]
Well, this is quite embarrassing.
Thank you for noticing!

However, it needs to be the second index. The fix is to swap the iterators on line 114:
fwd[j,i] = alphas[t-ARdim-1,j] + logQ[j,i] + py[i];

This time I actually tested the code, it now seems to work correctly. All files are updated.

**Comment by howardya** [comment]
Hi, can you help explain why must it be second index?

Any issue if I implement as I shown above? 

```
alphas[t-ARdim,i]=log_sum_exp(fwd[i,]); 
```

**Comment by kjartako** [comment]
It will simply not result in the correct alphas.

A quick example for nreg=2:
Using your proposed implementation:  alphas[t,1] will be calculated using logQ[1,1] and logQ[1,2] (common first index).
The current code: alphas[t,1] will be calculated using logQ[1,1] and logQ[2,1] (common second index).

**Comment by howardya** [comment]
Hi @kjartako 

What I meant was the following fix, which I suggested initially.
```
		for(i in 1:nreg){
		  for (j in 1:nreg){
			fwd[i,j] = alphas[t-ARdim-1,i] + logQ[i,j] + py[j];
		}
		  alphas[t-ARdim,i]=log_sum_exp(fwd[i,]);
		}
```
It should work.

It should be the same as your fix
```
		for(i in 1:nreg){
		  for (j in 1:nreg){
			fwd[j,i] = alphas[t-ARdim-1,j] + logQ[j,i] + py[i];
		}
		  alphas[t-ARdim,i]=log_sum_exp(fwd[,i]);
```

Would you agree?

Thank you.

**Comment by kjartako** [comment]
Oh, I see.
Yes, that would of course be equivalent 👍

**Comment by howardya** [comment]
Thanks for sharing the code! It is very useful!
